import os, sys, yaml

# NOTE: make_stub has been removed since the UAV project now provides the entry points.

def write_partitions_cmake(base_dir, partitions):
    cmake_file = os.path.join(base_dir, "Runner", "partitions.cmake")
    os.makedirs(os.path.dirname(cmake_file), exist_ok=True)

    with open(cmake_file, "w") as f:
        f.write("# Auto-generated by config.py\n")
        f.write("# Stub sources removed for shared library integration\n")
        # You can also remove PARTITION_SRCS here if your CMakeLists doesn't need them anymore

def write_start_rtos(base_dir, system, partitions):
    runner_dir = os.path.join(base_dir, "Runner")
    os.makedirs(runner_dir, exist_ok=True)
    # Changed the output file name to avoid confusion with main.c
    main_path = os.path.join(runner_dir, "start_rtos.c")

    with open(main_path, "w") as f:
        # Includes
        f.write('#include "model.h"\n')
        f.write('#include "types.h"\n')
        f.write('#include "process.h"\n')
        f.write('#include "scheduler.h"\n\n')

        # extern declarations (Provided by the C++ UAV Bridge)
        for part in partitions:
            for proc in part["processes"]:
                f.write(f"extern void {proc['entry']}(void);\n")
        f.write("\n")

        # Partition count
        f.write(f"#define NUMBER_OF_PARTITIONS {len(partitions)}\n\n")

        # Changed from int main() to void start_rtos(void)
        f.write("void start_rtos(void) \n{\n")
        f.write("    system_t sys = {\n")
        f.write(f"        .major_frame_ns = {system['major_frame_ns']}ULL,\n")
        f.write(f"        .num_partitions = {len(partitions)}\n")
        f.write("    };\n\n")

        f.write(f"    partition_t parts[NUMBER_OF_PARTITIONS];\n")
        for i, part in enumerate(partitions):
            f.write(f'    partition_init(&parts[{i}], "{part["name"]}", {part["duration_ns"]}ULL, {part["offset_ns"]}ULL);\n')
        f.write("\n")

        # Process definitions
        for i, part in enumerate(partitions):
            for j, proc in enumerate(part["processes"]):
                f.write(f"    process_t procs{i}_{j}[1] = {{\n")
                f.write("        {\n")
                f.write(f'            .name = "{proc["name"]}",\n')
                f.write(f"            .period_ns = {proc['period_ns']}ULL,\n")
                f.write(f"            .timecap_ns = {proc['timecap_ns']}ULL,\n")
                f.write(f"            .priority = {proc['priority']},\n")
                f.write(f"            .entry_point = {proc['entry']}\n")
                f.write("        }\n")
                f.write("    };\n")
        f.write("\n")

        # Attach processes
        for i, part in enumerate(partitions):
            for j, proc in enumerate(part["processes"]):
                f.write(f"    parts[{i}].procs = procs{i}_{j};\n")
                f.write(f"    parts[{i}].num_processes = 1;\n")
                f.write(f"    parts[{i}].id = {i};\n")
        f.write("    sys.parts = parts;\n\n")

        # Start processes
        f.write("    for (int i = 0; i < sys.num_partitions; ++i){\n")
        f.write("        for (int j = 0; j < sys.parts[i].num_processes; ++j){\n")
        f.write("            start_process(&sys.parts[i].procs[j], &sys.parts[i]);\n")
        f.write("        }\n")
        f.write("    }\n\n")

        # Run scheduler
        f.write("    run_scheduler(&sys);\n")
        f.write("}\n") # Removed return 0

def resolve_config_path(default_arg, base_dir):
    """
    Checks for YAML configuration in the following order:
    1. Parent directory (e.g., UAV project root when RTOS is a submodule)
    2. Explicit path passed as command line argument (if it exists)
    3. RTOS repository local directory (fallback default)
    """
    config_filename = os.path.basename(default_arg) if default_arg else "config.yaml"
    parent_dir = os.path.abspath(os.path.join(base_dir, ".."))

    # Candidate locations in priority order
    candidate_paths = [
        os.path.join(parent_dir, config_filename),        # ../config.yaml
        os.path.join(parent_dir, "rtos_config.yaml"),    # ../rtos_config.yaml
        os.path.abspath(default_arg) if default_arg else "", 
        os.path.join(base_dir, "config.yaml")             # ./config.yaml
    ]

    for path in candidate_paths:
        if path and os.path.isfile(path):
            print(f"[config.py] Found config file at: {path}")
            return path

    raise FileNotFoundError(
        f"Config file not found. Checked parent '{parent_dir}' and base '{base_dir}'."
    )

def main():
    if len(sys.argv) < 3:
        print("Usage: python config.py <config.yaml> <base_dir>")
        sys.exit(1)

    raw_config_arg, base_dir = sys.argv[1], sys.argv[2]
    
    # Resolve the configuration file path dynamically
    config_file = resolve_config_path(raw_config_arg, base_dir)

    with open(config_file, "r") as f:
        config = yaml.safe_load(f)

    system = config["system"]
    partitions = system["partitions"]

    # Generate partitions.cmake
    write_partitions_cmake(base_dir, partitions)

    # Generate start_rtos.c
    write_start_rtos(base_dir, system, partitions)

if __name__ == "__main__":
    main()